Revert "qcacld-3.0: Fix compile error of mdie"
../../../../../../kernel/nokia/msm8998/drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6058:14: error: argument 'mdie' of type 'uint8_t[]' (aka 'unsigned char[]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[])
                           ^
../../../../../../kernel/nokia/msm8998/drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1121:46: note: previously declared as 'uint8_t[3]' (aka 'unsigned char[3]') here
                tDot11fIEMobilityDomain * pDot11f, uint8_t mdie[SIR_MDIE_SIZE]);
                                                           ^
1 error generated.

This reverts commit 205fa7f309398d49010b9951c8b0b2179de0e604.