Makefile: Disable -Wasm-operand-widths & -Waddress-of-packed-member It's needed to build the kernel with clang-17.
../../../../../../kernel/nokia/msm8998/arch/arm64/include/asm/sysreg.h:254:43: error: value size does not match register size specified by the constraint and modifier [-Werror,-Wasm-operand-widths]
        asm volatile("mrs %0, sctlr_el1" : "=r" (val));
                                                 ^
../../../../../../kernel/nokia/msm8998/arch/arm64/include/asm/sysreg.h:254:20: note: use constraint modifier "w"
        asm volatile("mrs %0, sctlr_el1" : "=r" (val));
                          ^~
                          %w0
../../../../../../kernel/nokia/msm8998/arch/arm64/include/asm/sysreg.h:257:44: error: value size does not match register size specified by the constraint and modifier [-Werror,-Wasm-operand-widths]
        asm volatile("msr sctlr_el1, %0" : : "r" (val));
                                                  ^
../../../../../../kernel/nokia/msm8998/arch/arm64/include/asm/sysreg.h:257:31: note: use constraint modifier "w"
        asm volatile("msr sctlr_el1, %0" : : "r" (val));
                                     ^~
                                     %w0
2 errors generated.

../../../../../../kernel/nokia/msm8998/drivers/staging/qca-wifi-host-cmn/qdf/linux/src/qdf_nbuf.c:3535:27: error: taking address of packed member 'it_present' of class or structure 'ieee80211_radiotap_header' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]