Touchscreen-ST: Declare function It's needed for new clang versions.
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsCompensation.c:725:21: error: a function declar
ation without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int ALT_readChipInfo()
                    ^
                     void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTest.c:435:24: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int production_test_ito()
                       ^
                        void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTest.c:488:35: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int production_test_initialization()
                                  ^
                                   void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTest.c:546:27: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int ms_compensation_tuning()
                          ^
                           void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTest.c:585:27: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int ss_compensation_tuning()
                          ^
                           void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTest.c:623:25: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int lp_timer_calibration()
                        ^
                         void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTest.c:661:19: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int save_cx_tuning()
                  ^
                   void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsError.c:66:18: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int dumpErrorInfo(){
                 ^
                  void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTime.c:69:16: error: a function declaration wit
hout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
char* timestamp() {
               ^
                void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsIO.c:69:23: error: a function declaration witho
ut a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device * getDev()
                      ^
                       void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsIO.c:77:30: error: a function declaration witho
ut a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct i2c_client * getClient()
                             ^
                              void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:174:23: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int releaseInformation(){
                      ^
                       void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:697:14: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int flushFIFO() {
             ^
              void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:710:25: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int fts_disableInterrupt() {
                        ^
                         void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:723:24: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int fts_enableInterrupt() {
                       ^
                        void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:830:21: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int fts_system_reset() {
                    ^
                     void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:875:25: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int isSystemResettedDown() {
                        ^
                         void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:879:23: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int isSystemResettedUp() {
                      ^
                       void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:891:12: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int senseOn() {
           ^
            void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:905:13: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int senseOff() {
            ^
             void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:921:10: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int keyOn() {
         ^
          void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsTool.c:937:11: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int keyOff() {
          ^
           void

./../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsGesture.c:334:24: error: a function declaration
 without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int reloadCustomGesture() {
                       ^
                        void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFlash.c:605:18: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int fts_warm_boot()
                 ^
                  void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFlash.c:779:17: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int flash_unlock()
                ^
                 void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFlash.c:797:23: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int flash_erase_unlock()
                      ^
                       void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFlash.c:816:21: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int flash_full_erase()
                    ^
                     void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFlash.c:883:20: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int start_flash_dma()
                   ^
                    void

../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFrame.c:81:22: error: a function declaration wi
thout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int getChannelsLength() {
                     ^
                      void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFrame.c:369:16: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int getSenseLen() {
               ^
                void
../../../../../../kernel/nokia/msm8998/drivers/input/touchscreen/st/fts_lib/ftsFrame.c:385:16: error: a function declaration w
ithout a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int getForceLen() {
               ^
                void